'use client';
import { useEffect, useState } from 'react';
export default function StudioProofs({ order, revision }) {
  const [operations, setOperations] = useState({ activity: [], proofs: [] }); const [text, setText] = useState(() => order.items.map((i) => `${i.quantity} × ${i.name}\n${i.personalization || 'Enter exact personalization, color, and placement.'}`).join('\n\n')); const [link, setLink] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => { const controller = new AbortController(); fetch(`/api/studio/orders/${order.id}`, { signal: controller.signal }).then(async (res) => { const data = await res.json(); if (!res.ok) throw new Error(data.error); setOperations({ activity: data.activity || [], proofs: data.proofs || [] }); }).catch((e) => { if (e.name !== 'AbortError') setMessage(e.message); }); return () => controller.abort(); }, [order.id, revision]);
  const publish = async (event) => { event.preventDefault(); if (!window.confirm('Issue this proof for customer approval? Any earlier approval link will be superseded.')) return; setBusy(true); setMessage(''); try { const res = await fetch('/api/studio/proofs', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ orderId: order.id, text }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); setLink(`${window.location.origin}/proof/${data.id}#token=${data.token}`); const updated = await fetch(`/api/studio/orders/${order.id}`).then((r) => r.json()); setOperations({ activity: updated.activity || [], proofs: updated.proofs || [] }); setMessage('Proof link created. Send the link to the customer to request approval.'); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  return <div className="no-print"><section className="studio-panel studio-proof-panel"><p className="eyebrow">CUSTOMER APPROVAL</p><h3>One last look before stitching</h3><p>Production is blocked while an issued proof awaits approval. Quantity changes invalidate an existing approval.</p>{message && <p role="status">{message}</p>}
    <form className="order-form" onSubmit={publish}><label>Personalization proof<textarea required maxLength={15000} rows={6} value={text} onChange={(e) => setText(e.target.value)} /></label><button className="soft-button" type="submit" disabled={busy}>Create approval link</button></form>
    {link && <div><label>Customer approval link<input readOnly value={link} onFocus={(e) => e.target.select()} /></label><a className="soft-button" href={`mailto:${encodeURIComponent(order.email)}?subject=${encodeURIComponent('Please approve your Love & Co. personalization')}&body=${encodeURIComponent('Please review your personalization and approve it or request changes:\n\n' + link)}`}>Draft approval email</a><p className="helper">Copy this link now. It will not be displayed again after leaving this screen.</p></div>}
    {operations.proofs.map((p) => <details key={p.id}><summary>{p.status.replaceAll('_',' ')} · {new Date(p.created_at).toLocaleString()}</summary><pre className="proof-copy">{p.proof_text}</pre>{p.response && <p>Customer: {p.response}</p>}</details>)}
    </section><section className="studio-panel"><h3>Order activity</h3><ol className="studio-activity">{operations.activity.map((a) => <li key={a.id}><strong>{a.action}</strong><p>{a.actor} · {new Date(a.created_at).toLocaleString()}</p>{a.details?.fields && <small>{a.details.fields.map((f) => f.replaceAll('_',' ')).join(', ')}</small>}{a.details?.total_before !== undefined && <p>Total: ${Number(a.details.total_before).toFixed(2)} → ${Number(a.details.total_after).toFixed(2)}</p>}{a.details?.payment_before && <p>Payment: {a.details.payment_before} → {a.details.payment_after}</p>}</li>)}</ol>{!operations.activity.length && <p>Changes made after this upgrade will appear here.</p>}</section></div>;
}
