'use client';
import { useEffect, useState } from 'react';
const empty = { name: '', size: '', color: '', low_at: 5 };
export default function StudioInventory() {
  const [data, setData] = useState({ supplies: [], movements: [] }); const [draft, setDraft] = useState(empty); const [query, setQuery] = useState(''); const [lowOnly, setLowOnly] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => { const controller = new AbortController(); fetch('/api/studio/inventory', { signal: controller.signal }).then(async (res) => { const result = await res.json(); if (!res.ok) throw new Error(result.error); setData(result); }).catch((e) => { if (e.name !== 'AbortError') setMessage(e.message); }); return () => controller.abort(); }, []);
  const save = async (event) => { event.preventDefault(); setBusy(true); setMessage(''); try { const res = await fetch('/api/studio/inventory', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(draft) }); const result = await res.json(); if (!res.ok) throw new Error(result.error); setData((d) => ({ ...d, supplies: [...d.supplies, result.supply] })); setDraft(empty); setMessage('Supply added. Record a stock adjustment to add your opening quantity.'); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  const adjust = async (event, id) => { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setMessage(''); try { const res = await fetch('/api/studio/inventory', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, change: Number(form.get('change')), reason: form.get('reason') }) }); const result = await res.json(); if (!res.ok) throw new Error(result.error); setData(result); setMessage('Stock updated.'); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  const visible = data.supplies.filter((s) => `${s.name} ${s.size} ${s.color}`.toLowerCase().includes(query.toLowerCase()) && (!lowOnly || s.quantity <= s.low_at));
  return <section className="studio-panel"><p className="eyebrow">SUPPLY SHELF</p><h2>Blanks, sizes & colors</h2><p>{data.supplies.filter((s) => s.quantity <= s.low_at).length} supplies need restocking. Record usage as you stitch; orders do not deduct supplies automatically.</p>{message && <p role="status">{message}</p>}
    <details><summary>Add a supply</summary><form className="order-form" onSubmit={save}><div className="form-row">{[['name','Supply name'],['size','Size'],['color','Color']].map(([key,label]) => <label key={key}>{label}<input required={key === 'name'} maxLength={200} value={draft[key]} onChange={(e) => setDraft({ ...draft, [key]: e.target.value })} /></label>)}<label>Low-stock alert at<input type="number" min="0" max="100000" value={draft.low_at} onChange={(e) => setDraft({ ...draft, low_at: Number(e.target.value) })} /></label></div><button className="soft-button" type="submit" disabled={busy}>Add supply</button></form></details>
    <label>Search supplies<input type="search" value={query} onChange={(e) => setQuery(e.target.value)} /></label><label className="check-row"><input type="checkbox" checked={lowOnly} onChange={(e) => setLowOnly(e.target.checked)} />Only low stock</label>
    <div className="studio-supply-list">{visible.map((s) => <article key={s.id}><div className="queue-title"><div><h3>{s.name}</h3><p>{s.size} · {s.color}</p></div><strong>{s.quantity} on hand {s.quantity <= s.low_at && <span className="status-chip">Low stock</span>}</strong></div><form className="form-row" onSubmit={(e) => adjust(e,s.id)}><label>Quantity change<input name="change" type="number" step="1" min="-100000" max="100000" required placeholder="10 or −2" /></label><label>Reason<input name="reason" required maxLength={500} placeholder="Restock or order number…" /></label><button className="soft-button" type="submit" disabled={busy}>Adjust stock</button></form></article>)}</div>
    {!visible.length && <p>No supplies in this view. Add blanks or materials to start tracking stock.</p>}
    <details><summary>Recent stock changes</summary>{data.movements.slice(0,100).map((m) => <p key={m.id}>{data.supplies.find((s) => s.id === m.inventory_id)?.name} · {m.change > 0 ? '+' : ''}{m.change} · {m.reason} · {m.actor}</p>)}</details>
  </section>;
}
